### ISSUE TITLE
It is not possible to connect to multiple devies at the same time

### ISSUE THREAD

**Issue by mtttz** [Aritzherrero4/python-trionesControl#3]
I want to connect to several devices at the same time. This is currently not possible. The reason is the [following function of pygatt](https://github.com/peplin/pygatt/blob/50b13e21ccd10f51834a18aeac3fcc77bed1547f/pygatt/backends/gatttool/gatttool.py#L244):
```
    def start(self, reset_on_start=True, initialization_timeout=3):
        """
        Run gatttool to prepare for sending commands and monitoring the CLI tool
        output.

        :param bool reset_on_start: Perhaps due to a bug in gatttol or pygatt,
            but if the bluez backend isn't restarted, it can sometimes lock up
            the computer when trying to make a connection to HCI device.
```
When this function is called with `reset_on_start=True` all previous connections made by all other adapters are invalidated.

It is [currently called in this repository](https://github.com/Aritzherrero4/python-trionesControl/blob/6f7904dbec29b4d1db60fd85530472ca1d6eb3fe/trionesControl/trionesControl.py#L8) like this:

```
def connect(MAC):
    try:
        adapter = pygatt.GATTToolBackend()
        adapter.start()
        device = adapter.connect(MAC)
```
That means it is impossible to connect to two or more devices, becaus the call to `connect` will always invalidate the previous one.

An easy way to make multiple devies at the same time possible would be to add `reset_on_start` as keyword parameter to `connect` and pass it through to `pygatt.GATTToolBackend.start`.
This would allow users to create adapters and connect to devices without restarting the backend everytime.

**Comment by Aritzherrero4** [comment]
Tested and working just fine. I did not think of it since I had only one device to test at the time.
